version: '3'
services:
  tprn:
    build: .
    volumes:
      - .:/tprn
      - "${TPRN_DATA_DIR:-data}:/tprn/data"

  tprn-conda-env-build:
    build:
      context: .
      dockerfile: Dockerfile.conda.env.build
    volumes:
      - .:/tprn

volumes:
  data:
